# Generated by Django 4.1.1 on 2022-10-09 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('password', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'charity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('needs_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'needs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('website_link', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('follows', models.ManyToManyField(blank=True, to='comp9900.charity')),
                ('needs', models.ManyToManyField(blank=True, to='comp9900.needs')),
            ],
            options={
                'verbose_name': 'sponsor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp9900.charity')),
            ],
            options={
                'verbose_name': 'event',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='charity',
            name='needs',
            field=models.ManyToManyField(blank=True, to='comp9900.needs'),
        ),
    ]
