# Generated by Django 4.1.1 on 2022-11-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp9900', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='comp9900.needs'),
        ),
    ]
