# Generated by Django 4.1.1 on 2022-10-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp9900', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('help_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'help_area',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='help',
            field=models.ManyToManyField(blank=True, to='comp9900.help'),
        ),
    ]
