# Generated by Django 4.1.1 on 2022-10-11 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp9900', '0002_help_sponsor_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Sponsor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='comp9900.sponsor'),
        ),
    ]
