# Generated by Django 4.1.1 on 2022-11-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp9900', '0002_alter_event_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='content')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='if read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('charity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='comp9900.charity', verbose_name='sender')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_messages', to='comp9900.sponsor', verbose_name='receiver')),
            ],
        ),
    ]
