# Generated by Django 4.1.1 on 2022-10-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp9900', '0003_event_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Sponsor',
        ),
        migrations.AddField(
            model_name='event',
            name='Sponsor',
            field=models.ManyToManyField(blank=True, to='comp9900.sponsor'),
        ),
    ]
