# Generated by Django 4.1.1 on 2022-10-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='help',
            field=models.ManyToManyField(blank=True, to='comp9900.needs'),
        ),
    ]
